### ISSUE TITLE
Spotify stopped working

### ISSUE THREAD

**Issue by pattyland** [dfederlein/dnsbl-dfed#1]
Blocking `spclient.wg.spotify.com` causes Spotify to no longer work on any device

https://github.com/dfederlein/dnsbl-dfed/blob/master/spotifyads.txt#L31

See also: https://www.reddit.com/r/pihole/comments/cbt7dp/spclientwgspotifycom/

**Comment by dfederlein** [comment]
Usually I add these to the whitelist for pfblockerng (ie: These aren't meant for pihole, for that I'd use https://dbl.oisd.nl/ )
